# Generated by Django 3.1.5 on 2021-02-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cle', models.CharField(max_length=50)),
                ('commission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pas_ok', 'Commande annulée'), ('ok', 'Commande éffectué')], default='ok', max_length=20)),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('cin', models.CharField(max_length=30)),
                ('existance', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_vendeur', models.FloatField()),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('moq', models.IntegerField(default=1)),
                ('status', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='image_produit')),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profil_vendeur')),
                ('contact1', models.CharField(max_length=20)),
                ('contact2', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(max_length=20)),
                ('commune', models.CharField(blank=True, max_length=20, null=True)),
                ('quartier', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact1', models.CharField(max_length=20)),
                ('contact2', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(max_length=20)),
                ('commune', models.CharField(blank=True, max_length=20, null=True)),
                ('quartier', models.CharField(max_length=20)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profil_client')),
                ('produit', models.ManyToManyField(through='Client.ProduitUser', to='Client.Produit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='produituser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.user'),
        ),
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.vendeur'),
        ),
        migrations.CreateModel(
            name='PanierProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=0)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.commande')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.produit')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='produit',
            field=models.ManyToManyField(through='Client.PanierProduit', to='Client.Produit'),
        ),
        migrations.AddField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.user'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_paiement', models.CharField(choices=[('cash_livraison', 'Payer cash à la livraison')], default='cash_livraison', max_length=20)),
                ('montant_total', models.FloatField()),
                ('status', models.CharField(choices=[('en_attente', 'En entente'), ('refuse', 'Réfusé'), ('fait', 'Fait')], max_length=15)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(choices=[('abidjan', 'Livraison à abidjan'), ('interieur', "Livraison à l'interieur du pays")], max_length=20)),
                ('frais', models.FloatField()),
                ('date_livraison', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('annulee', 'Annulée'), ('faite', 'Faite')], max_length=20)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_produit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cmd', models.IntegerField()),
                ('date_cmd', models.DateTimeField(auto_now_add=True)),
                ('montant_cmd', models.FloatField()),
                ('libelle', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=30)),
                ('prix_vendeur', models.FloatField()),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('frais_livraison', models.FloatField()),
                ('adresse_livraison', models.CharField(max_length=100)),
                ('status_livraison', models.CharField(choices=[('en_cours', 'En cours'), ('annulee', 'Annulée'), ('faite', 'Faite')], default='en_cours', max_length=20)),
                ('moyen_paiement', models.CharField(max_length=100)),
                ('montant_total', models.FloatField()),
                ('status_paiement', models.CharField(choices=[('en_attente', 'En entente'), ('refuse', 'Réfusé'), ('fait', 'Fait')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('client', models.CharField(max_length=100)),
                ('vendeur', models.CharField(max_length=100)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.livreur')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.panier'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_produits', models.IntegerField()),
                ('note_livraison', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.livraison')),
            ],
        ),
    ]
