# Generated by Django 3.1.5 on 2021-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='produits_vendu',
            field=models.TextField(default='A remplacer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageproduit',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='profil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
