# Generated by Django 3.1.5 on 2021-03-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20210307_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduit',
            name='image',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/projet-commerce.appspot.com/o/produit_introuvable.jpeg?alt=media&token=e0b8e248-ac8d-476d-b222-47d485f18f88'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/projet-commerce.appspot.com/o/produit_introuvable.jpeg?alt=media&token=e0b8e248-ac8d-476d-b222-47d485f18f88'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.TextField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/projet-commerce.appspot.com/o/profil_inconnu.jpg?alt=media&token=4348dcfd-89c9-4c74-8a9c-65d75e6fadb5', null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='profil',
            field=models.TextField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/projet-commerce.appspot.com/o/profil_inconnu.jpg?alt=media&token=4348dcfd-89c9-4c74-8a9c-65d75e6fadb5', null=True),
        ),
    ]
