# Generated by Django 3.1.5 on 2021-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_historique_code_cmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(default='A renseigner', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendeur',
            name='adresse',
            field=models.CharField(default='A renseigner', max_length=255),
            preserve_default=False,
        ),
    ]
