# Generated by Django 3.1.5 on 2021-03-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20210323_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='moq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='ville',
        ),
    ]
